const icon = {
  eyeon: require('../assets/icon/eyeon.png'),
  eyeoff: require('../assets/icon/eyeoff.png'),
  Earn : require('../assets/icon/earn.png'),
  call: require('../assets/icon/call.png'),        
  logout:require('../assets/icon/logout.png'),
  frontArrow:require('../assets/icon/next.png'),
  drop:require('../assets/icon/drop.png'),

  rightArrow:require('../assets/icon/rightArrow.png'),
  leftArrow:require('../assets/icon/leftArrow.png'),
  slideRightArrow:require('../assets/icon/slideIndicatorRight.png'),
  slideLeftArrow:require('../assets/icon/slideIndicatorLeft.png'),
  bellIcon:require('../assets/icon/bellicon.png'),
  inquiryIcon: require('../assets/icon/inquiry.png'),
  bookingIcon: require('../assets/icon/booking.png'),
  calenderIcon:require('../assets/icon/calendar.png'),
  leftIndicator:require('../assets/icon/leftIndicator.png'),
  home:require('../assets/icon/HomeIcon.png'),
  inbox:require('../assets/icon/InboxIcon.png'),
  projects:require('../assets/icon/ProjectsIcon.png'),
  myteam:require('../assets/icon/MyteamIcon.png'),
  myteam:require('../assets/icon/MyteamIcon.png'),
  setting:require('../assets/icon/SettingIcon.png'),
  backArrow:require('../assets/icon/backArrow.png'),
  edit:require('../assets/icon/editIcon.png'),
  star:require('../assets/icon/star.png'),
  locationIcon:require('../assets/icon/location.png'),
  calendarIcon2:require('../assets/icon/calendar2.png'),
  callBlack:require("../assets/icon/callIcon.png"),
  chatBlack:require("../assets/icon/messageIcon.png"),
  envelopeBlack:require("../assets/icon/envelopeIcon.png"),
  leftBlack:require("../assets/icon/leftArrowBlack.png"),
  Stroke:require("../assets/icon/Stroke.png"),
  calenderIcon3:require("../assets/icon/Calendar3.png"),
  clock:require("../assets/icon/Clock.png"),
  profile2:require("../assets/icon/profile2.png"),
  addIcon:require("../assets/icon/Add2.png"),
  equalIcon:require("../assets/icon/equal.png"),
  stroke2:require("../assets/icon/Stroke2.png"),
 circleIcon:require("../assets/icon/Circle.png"),
 upload2:require("../assets/icon/upload2.png"),
 upload3:require("../assets/icon/upload3.png"),
 circlePlus: require ("../assets/icon/plus.png"),
 circleMinus : require ("../assets/icon/minus.png"),
 circleCross : require("../assets/icon/remove.png"),
 search : require("../assets/icon/search.png"),
 files : require("../assets/icon/files.png"),
 send : require("../assets/icon/send.png"),
 swap : require("../assets/icon/swap.png"),




 
//  closeCross : require("../asstes/icon/closeRound.png"),
};

export default icon;
